(()=>{
if(window.__chicCoCrud)return;window.__chicCoCrud=1;
const cfg={clientes:['clients','CL','cliente'],inventario:['products','PRD','producto'],procedimientos:['procedures','SRV','procedimiento'],enCurso:['activeProcedures','ACT','procedimiento en curso'],planes:['plans','PLN','plan'],citas:['appointments','CIT','cita'],facturacion:['invoices','FAC','factura'],usuarios:['users','USR','usuario']};
const skip=new Set(['id','passwordHash','permissions','productsUsed']);
const T=v=>String(v??'').trim(),L=v=>T(v).toLowerCase(),C=()=>cfg[currentModule],COL=c=>{state[c[0]]=Array.isArray(state[c[0]])?state[c[0]]:[];return state[c[0]]},LBL=(it,c=C())=>`${it.name||it.title||it.id} (${it.id})`;
function optsFor(k,v){let a=null;if(k==='clientId')a=clientOptions(v);if(k==='procedureId')a=procedureOptions(v);if(k==='productId')a=productOptions(v);if(k==='specialist')a=specialistOptions(v);if(k==='role')a=Object.keys(rolePresets).map(r=>({value:r,label:roleLabel(r)}));if(k==='paymentMethod')a=['Efectivo','Tarjeta'].map(x=>({value:x,label:x}));if(k==='area')a=['Belleza','Estetica'].map(x=>({value:x,label:x}));if(k==='status')a=['Pendiente','Confirmada','En curso','Atendida','Cancelada','En progreso','Pausado','Finalizado','Activo','Completado'].map(x=>({value:x,label:x}));return a?`<select name='${escapeHtml(k)}'>${a.map(o=>`<option value='${escapeHtml(o.value)}' ${String(o.value)===String(v)?'selected':''}>${escapeHtml(o.label)}</option>`).join('')}</select>`:null}
function field(k,v){let o=optsFor(k,v);if(o)return wrap(k,o);if(typeof v==='boolean')return wrap(k,`<select name='${escapeHtml(k)}'><option value='true' ${v?'selected':''}>Activo</option><option value='false' ${!v?'selected':''}>Pausado</option></select>`);if(k==='notes'||k==='aftercare')return `<label class='field full'><span>${escapeHtml(k)}</span><textarea name='${escapeHtml(k)}'>${escapeHtml(v||'')}</textarea></label>`;let type=typeof v==='number'||['stock','min','cost','price','duration','sessions','sessionsTotal','sessionsDone','intervalDays','paid','total','productQty','serviceAmount','productAmount','ivaRate'].includes(k)?'number':k==='time'?'time':/(date|visit|start|next|expiration|purchase|started)$/i.test(k)?'date':'text';return wrap(k,`<input name='${escapeHtml(k)}' type='${type}' value='${escapeHtml(v??'')}' ${type==='number'?'min=0 step=any':''}>`)}
function wrap(k,html){return `<label class='field'><span>${escapeHtml(k)}</span>${html}</label>`}
function modal(){let m=document.querySelector('#crudModal');if(m)return m;m=document.createElement('div');m.id='crudModal';m.className='crud-modal';m.innerHTML=`<section class='crud-dialog'><button type='button' class='crud-close' data-crud-close>x</button><h3>Editar</h3><form class='crud-form'><div class='crud-grid' data-crud-fields></div><div class='crud-actions'><button class='secondary-action' type='button' data-crud-close>Cancelar</button><button class='primary-action'>Guardar</button></div></form></section>`;document.body.appendChild(m);return m}
function openEdit(){let c=C(),s=document.querySelector('[data-crud-select]'),it=c&&COL(c).find(x=>x.id===s?.value);if(!it){showToast('Seleccione un registro');return}let m=modal();m.dataset.module=currentModule;m.dataset.id=it.id;m.querySelector('h3').textContent=`Editar ${c[2]}`;m.querySelector('[data-crud-fields]').innerHTML=Object.keys(it).filter(k=>!skip.has(k)).map(k=>field(k,it[k])).join('');m.classList.add('is-open')}
function val(c,it,next){if(c[0]==='clients'&&(!T(next.name)||!T(next.phone)))return'El cliente necesita nombre y telefono';if(c[0]==='products'&&(!T(next.name)||Number(next.stock)<0))return'El producto necesita nombre y stock valido';if(c[0]==='appointments'){let dup=state.appointments.find(a=>a.id!==it.id&&a.date===next.date&&a.time===next.time&&L(a.specialist)===L(next.specialist)&&!['Atendida','Cancelada'].includes(a.status));if(dup&&!['Atendida','Cancelada'].includes(next.status))return'Ese especialista ya tiene una cita en esa fecha y hora'}if(c[0]==='plans'&&Number(next.sessionsDone)>Number(next.sessionsTotal))return'Las sesiones hechas no pueden superar el total';if(c[0]==='users'&&((it.id==='USR-000'&&next.active===false)||(it.id===state.currentUserId&&next.active===false)))return'Ese usuario no se puede pausar';return''}
function move(p,type,q,prev,next,reason,ref=''){if(!p||!q)return;state.stockMovements=state.stockMovements||[];state.stockMovements.unshift({id:nextId('MOV',state.stockMovements),productId:p.id,type,quantity:Math.abs(Number(q)),previousStock:prev,balanceAfter:next,unitCost:Number(p.cost||0),supplier:p.supplier||'',reference:ref,reason,date:todayISO(),userId:currentUser()?.id||'',userName:currentUser()?.name||'Sistema'})}
function invoiceStock(before,after){let oq=Number(before.productQty||0),nq=Number(after.productQty||0);if(before.productId===after.productId){let p=getProduct(after.productId);if(!p)return;let d=nq-oq;if(!d)return;let prev=Number(p.stock||0),next=prev-d;if(next<0){showToast('No hay stock suficiente');return false}p.stock=next;move(p,d>0?'Salida':'Entrada',d,prev,next,`Edicion de factura ${after.id}`,after.id);return true}let old=getProduct(before.productId),neu=getProduct(after.productId);if(old&&oq){let prev=Number(old.stock||0),next=prev+oq;old.stock=next;move(old,'Entrada',oq,prev,next,`Producto devuelto por edicion de factura ${before.id}`,before.id)}if(neu&&nq){let prev=Number(neu.stock||0),next=prev-nq;if(next<0){showToast('No hay stock suficiente');return false}neu.stock=next;move(neu,'Salida',nq,prev,next,`Producto aplicado por edicion de factura ${after.id}`,after.id)}return true}
function saveEdit(e){e.preventDefault();let m=modal(),c=cfg[m.dataset.module],arr=COL(c),it=arr.find(x=>x.id===m.dataset.id);if(!it)return;let next={...it},data=Object.fromEntries(new FormData(e.target).entries());Object.keys(data).forEach(k=>{let old=it[k];next[k]=typeof old==='number'?Number(data[k]||0):typeof old==='boolean'?data[k]==='true':data[k]});let msg=val(c,it,next);if(msg){showToast(msg);return}let before=c[0]==='invoices'?{...it}:null;Object.assign(it,next);if(c[0]==='invoices'&&invoiceStock(before,it)===false)return;if(c[0]==='users')it.permissions=rolePresets[it.role]?.permissions||it.permissions;modal().classList.remove('is-open');persistAndRender('Registro actualizado')}
function refs(c,it){if(c[0]==='clients'&&[...state.plans,...state.appointments,...state.invoices,...state.activeProcedures].some(r=>r.clientId===it.id))return'Ese cliente tiene historial relacionado';if(c[0]==='products'&&[...state.procedures,...state.invoices].some(r=>r.productId===it.id))return'Ese producto esta usado en procedimientos o facturas';if(c[0]==='procedures'&&[...state.plans,...state.appointments,...state.invoices,...state.activeProcedures].some(r=>r.procedureId===it.id))return'Ese procedimiento tiene historial relacionado';return''}
function del(){let c=C(),s=document.querySelector('[data-crud-select]'),arr=COL(c),it=arr.find(x=>x.id===s?.value);if(!it){showToast('Seleccione un registro');return}if(c[0]==='users'){if(it.id==='USR-000'||it.id===state.currentUserId){showToast('Ese usuario no se puede eliminar');return}it.active=false;persistAndRender('Usuario pausado');return}let r=refs(c,it);if(r){showToast(r);return}if(!confirm(`Eliminar ${c[2]}: ${LBL(it,c)}?`))return;if(c[0]==='invoices'&&it.productId&&Number(it.productQty)>0){let p=getProduct(it.productId);if(p){let prev=Number(p.stock||0),next=prev+Number(it.productQty);p.stock=next;move(p,'Entrada',it.productQty,prev,next,`Factura eliminada ${it.id}`,it.id)}}state[c[0]]=arr.filter(x=>x.id!==it.id);persistAndRender('Registro eliminado')}
function dup(){let c=C(),s=document.querySelector('[data-crud-select]'),it=c&&COL(c).find(x=>x.id===s?.value);if(!it)return showToast('Seleccione un registro');if(['users','invoices'].includes(c[0]))return showToast('Ese modulo no se duplica por seguridad');let cp=clone(it);cp.id=nextId(c[1],COL(c));if(cp.name)cp.name+=' copia';if(cp.title)cp.title+=' copia';if(c[0]==='appointments')cp.status='Pendiente';COL(c).unshift(cp);persistAndRender('Registro duplicado')}
function csv(){let c=C();if(!c)return;let arr=COL(c),keys=[...new Set(arr.flatMap(o=>Object.keys(o).filter(k=>!['passwordHash','permissions'].includes(k))))],q=v=>`"${String(v??'').replaceAll('"','""')}"`,body=[keys.join(','),...arr.map(o=>keys.map(k=>q(typeof o[k]==='object'?JSON.stringify(o[k]):o[k])).join(','))].join('\n');dl(`chic-co-${currentModule}-${todayISO()}.csv`,body,'text/csv;charset=utf-8')}
function dl(name,content,type){let b=new Blob([content],{type}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(u)}
function backup(){syncCurrentBranchData();dl(`chic-co-respaldo-${todayISO()}.json`,JSON.stringify(state,null,2),'application/json;charset=utf-8')}
function restore(file){let r=new FileReader();r.onload=()=>{try{let data=JSON.parse(r.result);if(!confirm('Importar este respaldo reemplazara los datos actuales. Continuar?'))return;state=typeof normalizeStateSnapshot==='function'?normalizeStateSnapshot(data):data;saveState();renderAll();showToast('Respaldo importado')}catch(e){showToast('Respaldo invalido')}};r.readAsText(file)}
function tools(){let c=C(),p=elements.viewContent.querySelector('.records-panel');if(!c||!p||p.querySelector('.crud-tools'))return;let arr=COL(c),sel=arr[0]?.id||'',w=canWrite(currentModule),sec=document.createElement('section');sec.className='crud-tools';sec.innerHTML=`<div class='crud-tools-main'><label class='field'><span>Gestionar registro</span><select data-crud-select>${arr.map(x=>`<option value='${escapeHtml(x.id)}' ${x.id===sel?'selected':''}>${escapeHtml(LBL(x,c))}</option>`).join('')}</select></label><div class='crud-buttons'><button class='row-action' data-crud-edit ${w?'':'disabled'}>Editar</button><button class='row-action is-muted' data-crud-dup ${w?'':'disabled'}>Duplicar</button><button class='row-action is-warning' data-crud-del ${w?'':'disabled'}>Eliminar</button><button class='row-action is-muted' data-crud-csv>CSV</button><button class='row-action is-muted' data-crud-print>Imprimir</button></div></div>${currentUser()?.role==='super'?`<div class='crud-buttons'><button class='secondary-action' data-crud-backup>Exportar respaldo</button><button class='secondary-action' data-crud-import>Importar respaldo</button><input type='file' accept='application/json,.json' data-crud-file hidden></div>`:''}`;p.prepend(sec)}
const addC=addClient;addClient=d=>{if(d.email&&state.clients.some(x=>L(x.email)===L(d.email)))return showToast('Ya existe un cliente con ese email');addC(d)};const addA=addAppointment;addAppointment=d=>{let dup=state.appointments.some(a=>a.date===d.date&&a.time===d.time&&L(a.specialist)===L(d.specialist)&&!['Atendida','Cancelada'].includes(a.status));if(dup)return showToast('Ese especialista ya tiene una cita en esa fecha y hora');addA(d)};const rv=renderView;renderView=()=>{rv();tools()};
document.addEventListener('click',e=>{if(e.target.closest('[data-crud-close]'))modal().classList.remove('is-open');else if(e.target.closest('[data-crud-edit]')){if(requireWrite(currentModule))openEdit()}else if(e.target.closest('[data-crud-del]')){if(requireWrite(currentModule))del()}else if(e.target.closest('[data-crud-dup]')){if(requireWrite(currentModule))dup()}else if(e.target.closest('[data-crud-csv]'))csv();else if(e.target.closest('[data-crud-print]'))print();else if(e.target.closest('[data-crud-backup]'))backup();else if(e.target.closest('[data-crud-import]'))document.querySelector('[data-crud-file]')?.click()});
document.addEventListener('change',e=>{let f=e.target.closest('[data-crud-file]');if(f?.files?.[0]){restore(f.files[0]);f.value=''}});document.addEventListener('submit',e=>{if(e.target.classList.contains('crud-form'))saveEdit(e)});document.addEventListener('keydown',e=>{if(e.key==='Escape')modal().classList.remove('is-open')});
let st=document.createElement('style');st.textContent='.crud-tools{display:grid;gap:10px;padding:12px;border:1px solid rgba(36,49,50,.08);background:rgba(251,251,244,.92);border-radius:var(--radius)}.crud-tools-main{display:grid;grid-template-columns:minmax(220px,1fr) auto;gap:10px;align-items:end}.crud-buttons,.crud-actions{display:flex;gap:8px;flex-wrap:wrap;align-items:center;justify-content:flex-end}.crud-modal{position:fixed;inset:0;z-index:70;display:none;place-items:center;padding:20px;background:rgba(5,5,5,.58)}.crud-modal.is-open{display:grid}.crud-dialog{position:relative;width:min(860px,100%);max-height:min(760px,calc(100vh - 40px));overflow:auto;padding:18px;border:1px solid rgba(240,212,162,.18);background:#fff;border-radius:var(--radius);box-shadow:0 24px 70px rgba(0,0,0,.32)}.crud-dialog h3{margin:0 38px 14px 0;color:var(--ink);font-size:18px}.crud-close{position:absolute;top:12px;right:12px;width:32px;height:32px;border:0;color:var(--gold-soft);background:#050505;border-radius:var(--radius);font-size:16px}.crud-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.crud-form{display:grid;gap:14px}@media(max-width:860px){.crud-tools-main,.crud-grid{grid-template-columns:1fr}.crud-buttons>*{flex:1 1 140px}}@media print{.topbar,.sidebar,.form-panel,.toolbar,.crud-tools,.toast,.modal-backdrop,.crud-modal{display:none!important}.app-shell{display:block!important;width:100%!important}body,.operations-panel,.records-panel{background:#fff!important;box-shadow:none!important}}';document.head.appendChild(st);if(document.body.classList.contains('is-authenticated'))tools();
})();
